version: 2
formats: all

build:
  image: latest

python:
  version: 3.7
  system_packages: true
  install:
    - method: pip
      path: .
      extra_requirements:
        - sphinx

sphinx:
   configuration: doc/source/conf.py
