dist: xenial
language: python
python:
  - "3.7"
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
cache:
  pip: true
  directories:
    - .venv
install:
  - pip install pipenv
  - pipenv install --dev --three
script: pipenv run -- ./utils/git/pre-push
